# Generated by Django 5.2.8 on 2026-03-09 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewsession',
            old_name='start_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='interviewsession',
            old_name='expression_score',
            new_name='emotion_score',
        ),
        migrations.RenameField(
            model_name='interviewsession',
            old_name='feedback_text',
            new_name='feedback',
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
