# Generated by Django 5.2.8 on 2026-06-03 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ongoinginterviewsession',
            name='id',
        ),
        migrations.AddField(
            model_name='completedinterviewsession',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ongoinginterviewsession',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ongoing_session', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
