# Generated by Django 5.2.8 on 2026-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_rename_start_time_interviewsession_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='emotion_score',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='eye_contact_score',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='emotion_score_total',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='eye_score_total',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='frame_count',
            field=models.IntegerField(default=0.0),
        ),
    ]
