# Generated by Django 5.2.8 on 2026-06-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_remove_ongoinginterviewsession_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedinterviewsession',
            name='angry',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='completedinterviewsession',
            name='disgusted',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='completedinterviewsession',
            name='happy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='completedinterviewsession',
            name='neutral',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='completedinterviewsession',
            name='sad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='completedinterviewsession',
            name='scared',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='completedinterviewsession',
            name='shocked',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='completedinterviewsession',
            name='unknown',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ongoinginterviewsession',
            name='angry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ongoinginterviewsession',
            name='disgusted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ongoinginterviewsession',
            name='happy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ongoinginterviewsession',
            name='neutral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ongoinginterviewsession',
            name='sad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ongoinginterviewsession',
            name='scared',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ongoinginterviewsession',
            name='shocked',
            field=models.IntegerField(default=0),
        ),
    ]
