# Generated by Django 5.2.8 on 2026-06-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_completedinterviewsession_angry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoinginterviewsession',
            name='current_question',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ongoinginterviewsession',
            name='question_answer_times',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ongoinginterviewsession',
            name='question_elapsed_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ongoinginterviewsession',
            name='question_list',
            field=models.JSONField(default=list),
        ),
    ]
