# Generated by Django 5.2.8 on 2026-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_remove_interviewsession_emotion_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
