# Generated by Django 5.2.8 on 2026-05-24 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interviewsession_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
