# Generated by Django 5.2.8 on 2026-06-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_ongoinginterviewsession_current_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ongoinginterviewsession',
            name='current_question',
        ),
        migrations.AddField(
            model_name='completedinterviewsession',
            name='question_answer_times',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='completedinterviewsession',
            name='question_list',
            field=models.JSONField(default=list),
        ),
    ]
