# Generated by Django 5.2.8 on 2026-05-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_alter_interviewsession_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewsession',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='past_analysis_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
